// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDujkKg_f1UEsliQpUrW-QGLBptWUVMANg',
    appId: '1:913961761802:web:d2be2d91928882a9c8b3f3',
    messagingSenderId: '913961761802',
    projectId: 'blissiq-dd736',
    authDomain: 'blissiq-dd736.firebaseapp.com',
    storageBucket: 'blissiq-dd736.firebasestorage.app',
    measurementId: 'G-PCB8SX1CPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjaqDjucwGdPgmrgKvJrStonWv6Y1l-38',
    appId: '1:913961761802:android:7d09add5d444ab96c8b3f3',
    messagingSenderId: '913961761802',
    projectId: 'blissiq-dd736',
    storageBucket: 'blissiq-dd736.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnmd2Bw-8u32C54qPuduK_l9Cd8VOEB3k',
    appId: '1:913961761802:ios:b2a1097a2f79a5d1c8b3f3',
    messagingSenderId: '913961761802',
    projectId: 'blissiq-dd736',
    storageBucket: 'blissiq-dd736.firebasestorage.app',
    iosBundleId: 'com.blissiq.admin',
  );
}
